/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSynthesisRouteImport } from './routes/_app/synthesis'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppMfaRouteImport } from './routes/_app/mfa'
import { Route as AppDeploymentRouteImport } from './routes/_app/deployment'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConsultationRouteImport } from './routes/_app/consultation'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSynthesisRoute = AppSynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppMfaRoute = AppMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentRoute = AppDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationRoute = AppConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/consultation': typeof AppConsultationRoute
  '/dashboard': typeof AppDashboardRoute
  '/deployment': typeof AppDeploymentRoute
  '/mfa': typeof AppMfaRoute
  '/security': typeof AppSecurityRoute
  '/sessions': typeof AppSessionsRoute
  '/synthesis': typeof AppSynthesisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/consultation': typeof AppConsultationRoute
  '/dashboard': typeof AppDashboardRoute
  '/deployment': typeof AppDeploymentRoute
  '/mfa': typeof AppMfaRoute
  '/security': typeof AppSecurityRoute
  '/sessions': typeof AppSessionsRoute
  '/synthesis': typeof AppSynthesisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/consultation': typeof AppConsultationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deployment': typeof AppDeploymentRoute
  '/_app/mfa': typeof AppMfaRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/synthesis': typeof AppSynthesisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/audit'
    | '/consultation'
    | '/dashboard'
    | '/deployment'
    | '/mfa'
    | '/security'
    | '/sessions'
    | '/synthesis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/audit'
    | '/consultation'
    | '/dashboard'
    | '/deployment'
    | '/mfa'
    | '/security'
    | '/sessions'
    | '/synthesis'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/consultation'
    | '/_app/dashboard'
    | '/_app/deployment'
    | '/_app/mfa'
    | '/_app/security'
    | '/_app/sessions'
    | '/_app/synthesis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/synthesis': {
      id: '/_app/synthesis'
      path: '/synthesis'
      fullPath: '/synthesis'
      preLoaderRoute: typeof AppSynthesisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mfa': {
      id: '/_app/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AppMfaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployment': {
      id: '/_app/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof AppDeploymentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultation': {
      id: '/_app/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof AppConsultationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppConsultationRoute: typeof AppConsultationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeploymentRoute: typeof AppDeploymentRoute
  AppMfaRoute: typeof AppMfaRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSynthesisRoute: typeof AppSynthesisRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppConsultationRoute: AppConsultationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeploymentRoute: AppDeploymentRoute,
  AppMfaRoute: AppMfaRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSynthesisRoute: AppSynthesisRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
